project_name: "peft_lora_eval"

mode: "test"

# PEFT method
methods: ["base"]
active_method: "base"

# Model configuration
model:
#  model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
#  model_name_or_path: "meta-llama/Llama-3.2-3B-Instruct"
  model_name_or_path: "meta-llama/Llama-3.2-3B"

# Dataset configuration
dataset_name: "yahma/alpaca-cleaned"

dataloader:
  batch_size: 2

# Logging & experiment tracking
logging:
  log_every: 100
  checkpoint_step: 1000
  use_wandb: True