project_name: "peft_lora_eval"

model:
  model_name_or_path: "meta-llama/Llama-3.2-3B"

dataset:
  name: "yahma/alpaca-cleaned"
  subset: null
  val_ratio: 0.05
  test_ratio: 0.05

dataloader:
  batch_size: 2
  pad_to_multiple_of: null

training:
  num_epochs: 3
  num_training_steps: 0
  grad_accumulation_steps: 4
  optimizer:
    name: "paged_adamw_8bit"
    weight_decay: 0.01
    betas: [0.9, 0.95]
    eps: 0.00000007
  scheduler:
    name: "linear"
    num_warmup_steps: 0

logging:
  log_every: 500
  checkpoint_steps: 100
  log_level: "INFO"
  use_wandb: true
  wandb_project: "peft_lora_eval"


benchmark:
  batch_size: 32
  tasks:
    - "arc_challenge"
#    - "hellaswag"
#    - "mmlu"
#    - "truthfulqa_mc2"
#    - "winogrande"
#    - "gsm8k"
  metrics:
    arc_challenge: "acc_norm,none"
#    hellaswag: "acc_norm,none"
#    mmlu: "acc,none"
#    truthfulqa_mc2: "acc,none"
#    winogrande: "acc,none"
#    gsm8k: "exact_match,strict-match"
  num_fewshot: null
  limit: null
  use_cache: false

runtime:
  seed: 17
  merge: false
  use_small_model: false
  base_path: "./"
